# Generated by Django 3.2.25 on 2025-09-23 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceTranscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file_name', models.CharField(blank=True, max_length=255)),
                ('audio_file_size', models.PositiveIntegerField(blank=True, null=True)),
                ('audio_duration', models.FloatField(blank=True, null=True)),
                ('audio_format', models.CharField(blank=True, max_length=50)),
                ('speech_text', models.TextField()),
                ('latex_output', models.TextField(blank=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('transcribing', 'Transcribing'), ('translating', 'Translating'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('tags', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_transcriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='voicetranscription',
            index=models.Index(fields=['user', '-created_at'], name='voice_voice_user_id_6de831_idx'),
        ),
        migrations.AddIndex(
            model_name='voicetranscription',
            index=models.Index(fields=['user', 'status'], name='voice_voice_user_id_75ea95_idx'),
        ),
        migrations.AddIndex(
            model_name='voicetranscription',
            index=models.Index(fields=['user', 'is_favorite'], name='voice_voice_user_id_f877ec_idx'),
        ),
    ]
