# Generated by Django 3.2.25 on 2025-09-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='unique_id',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
