# Generated by Django 3.2.25 on 2025-09-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_document_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='unique_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
