# Generated by Django 3.2.25 on 2025-09-11 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_folder_parent_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='#3b82f6', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='notes.Tag'),
        ),
    ]
