# Generated by Django 3.2.25 on 2025-09-12 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_image'),
    ]

    operations = [
    ]
