# Generated by Django 3.2.25 on 2025-09-13 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0010_auto_20250912_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.TextField(help_text='Question or prompt')),
                ('back', models.TextField(help_text='Answer or explanation')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('interval_days', models.PositiveIntegerField(default=1, help_text='Days until next review')),
                ('repetitions', models.PositiveIntegerField(default=0, help_text='Number of times reviewed')),
                ('ease_factor', models.FloatField(default=2.5, help_text='Ease factor for spaced repetition')),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now, help_text='When to review next')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flashcards', to='notes.folder')),
                ('tags', models.ManyToManyField(blank=True, related_name='flashcards', to='notes.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review', 'created_at'],
            },
        ),
    ]
