# Generated by Django 3.2.25 on 2025-09-13 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20250913_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcardfolder',
            name='note_folder',
            field=models.ForeignKey(blank=True, help_text='Regular note folder this flashcard folder belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flashcard_folders', to='notes.folder'),
        ),
    ]
