use_default_settings: true

server:
  secret_key: "hang-searxng-local-dev-key-2026"
  limiter: false

search:
  formats:
    - html
    - json

engines:
  - name: google images
    engine: google_images
    shortcut: gimg
    disabled: false
  - name: ahmia
    disabled: true
  - name: torch
    disabled: true
  - name: artic
    disabled: true
